---
- name: Ensure extra manifests path exists
  file:
    path: "{{ manifests_path }}"
    state: directory

- name: Create the chrony NTP manifest
  template:
    src: templates/03-chrony-ntp.yaml
    dest: "{{ manifests_path }}/03-chrony-ntp.yaml"
  when: ntp_server != ''
