apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 03-chrony-ntp
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,{{ lookup('template', 'templates/chrony.conf', convert_data=False) | string | b64encode }}
        mode: 420
        overwrite: true
        path: /etc/chrony.conf
        user:
          name: root
