- name: Create temporary directory
  tempfile:
    state: directory
  register: temporary_directory

- name: Copy pull secret
  ansible.builtin.copy:
    content: "{{ pull_secret }}"
    dest: "{{ temporary_directory.path }}/pull_secret"

- name: Login to private registry
  shell: "podman login --username {{ provisioner_cluster_registry_user }} --password {{ provisioner_cluster_registry_password }} --tls-verify=false"

- name: Copy template to temporary path
  template:
    src: templates/icsp.yaml.j2
    dest: "{{ temporary_directory.path }}/icsp.yaml"

- name: Mirror images to internal registry
  include: mirror_image.yml image={{ item }}
  ignore_errors: true
  with_items:
    - quay.io/ocpmetal/s3server
    - quay.io/jparrill/s3server
    - quay.io/ocpmetal/assisted-service
    - quay.io/ocpmetal/assisted-installer
    - quay.io/ocpmetal/assisted-installer-agent
    - quay.io/ocpmetal/ocp-metal-ui
    - quay.io/ocpmetal/bm-inventory
    - quay.io/ocpmetal/assisted-installer-controller
    - quay.io/ocpmetal/assisted-iso-create
    - quay.io/ocpmetal/ocp-metal-ui-tests
    - quay.io/ocpmetal/postgresql-12-centos7
    - quay.io/ocpmetal/s3-object-expirer
    - quay.io/ocpmetal/assisted-installer-controller-ocp
    - quay.io/ocpmetal/swagger-codegen-cli:2.4.15
    - quay.io/ocpmetal/agent
    - quay.io/ocpmetal/assisted-ignition-generator:stable.24.09.2020-22.20
    - quay.io/ocpmetal/connectivity_check
    - quay.io/ocpmetal/inventory
    - quay.io/sameersbn/squid
    - quay.io/coreos/coreos-installer:release
    - quay.io/ohadlevy/kexec
    - quay.io/bitnami/wildfly
    - quay.io/ocpmetal/assisted-installer-controller-ocp:latest
    - quay.io/mavazque/s3cmd
    - quay.io/jparrill/assisted-service-operator-bundle:0.0.1
    - quay.io/jparrill/assisted-service-index:0.0.1
    - quay.io/openshift/origin-cli:latest
    - registry.access.redhat.com/ubi8/ubi-minimal:latest
    - quay.io/ocpmetal/assisted-service-operator-bundle:latest
    - quay.io/ocpmetal/assisted-service-index:latest
    - k8s.gcr.io/pause:3.5
    - quay.io/ocpmetal/assisted-installer-controller:latest

- name: Copy local kubeconfig to remote server if set
  ansible.builtin.copy:
    src: "{{ provisioner_cluster_kubeconfig }}"
    dest: "{{ temporary_directory.path }}/kubeconfig"

- name: Apply generated icsp
  ansible.builtin.shell:
    cmd: oc apply -f ./icsp.yaml
    chdir: "{{ temporary_directory.path }}"
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ temporary_directory.path }}/kubeconfig"

- name: fix mirrors in masters to don't mirror by digest
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'fix_master_mirrors.sh.j2') }}"
  environment:
    KUBECONFIG: "{{ temporary_directory.path }}/kubeconfig"

- name: Generate merged credentials
  ansible.builtin.shell:
    cmd: "jq -s '.[0] * .[1]' {{ temporary_directory.path }}/pull_secret $XDG_RUNTIME_DIR/containers/auth.json > {{ temporary_directory.path }}/merged_creds.json"

- name: Mirror release image for spoke clusters
  ansible.builtin.shell:
    cmd: "oc adm -a {{ temporary_directory.path }}/merged_creds.json release new --from-release=quay.io/openshift-release-dev/ocp-release:{{ mirror_version_spoke_release }} --mirror={{ provisioner_cluster_registry }}/ocp4 --to-image={{ provisioner_cluster_registry }}/ocp4:{{ mirror_version_spoke_release }}"
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ temporary_directory.path }}/kubeconfig"

