---
- name: Configure cluster
  block:
    - block:
      - name: Query for the host ID, there is only one as is SNO
        shell: "aicli list hosts | grep {{ cluster_name }} | cut -d '|' -f 4"
        register: host_id
        when: hostname is defined

      - name: Set the hostname for the given host_id
        shell: "aicli update host {{ host_id.stdout | trim }} -P name={{ hostname }}"
        when: host_id | length > 0
      when: hostname is defined

    - name: Wait until cluster is ready to be installed
      shell: "aicli list cluster | grep {{ cluster_name }} |  cut -d '|' -f4 | tr -d ' '"
      register: cluster_ready
      until: cluster_ready.stdout == "ready"
      retries: 100
      delay: 30

    - name: Install cluster
      shell: "aicli start cluster {{ cluster_name }}"
  environment:
    AI_URL: "{{ ai_url }}"

