
- name: Eject media
  uri:
    url: "https://{{bmc_address}}/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.EjectMedia"
    validate_certs: no
    method: POST
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    headers:
      content-type: application/json
      accept: application/json
    body_format: json
    body: "{}"
    status_code: 204
  ignore_errors: true

- name: Get storage controllers
  uri:
    url: "https://{{bmc_address}}/redfish/v1/Systems/System.Embedded.1/Storage"
    validate_certs: no
    method: GET
    return_content: yes
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    headers:
      content-type: application/json
      accept: application/json
  register: controllers_response
  ignore_errors: true

- name: Get storage controllers
  set_fact:
    controllers: "{{ controllers_response | json_query('json.Members[*][\"@odata.id\"]') }}"

- name: Get virtual disks
  uri:
    url: "https://{{bmc_address}}{{ item }}/Volumes"
    validate_certs: no
    method: GET
    return_content: yes
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    headers:
      content-type: application/json
      accept: application/json
  register: volumes_responses
  ignore_errors: true
  with_items: "{{ controllers }}"

- name: Get virtual volumes
  set_fact:
    volumes: "{{ volumes_responses | json_query('results[*].json.Members[*][\"@odata.id\"]') | flatten}}"

- name: Initialize volume
  include_tasks: init_volume.yaml
  with_items: "{{ volumes }}"

- name: Mount ISO
  community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{bmc_address}}"
        username: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        virtual_media:
           image_url: "{{ iso_url }}/{{ iso_name }}"
           media_types:
              - CD
              - DVD

- name: Set Boot once
  idrac_redfish_config:
      category: Manager
      command:
        - SetManagerAttributes
      manager_attribute_name:  VirtualMedia.1.BootOnce
      manager_attribute_value: Enabled
      baseuri: "{{bmc_address}}"
      username: "{{ bmc_user }}"
      password: "{{ bmc_password }}"

- name: Set Boot Override to VirtualMedia
  idrac_redfish_config:
      category: Manager
      command:
        - SetManagerAttributes
      manager_attribute_name:  ServerBoot.1.FirstBootDevice
      manager_attribute_value: "VCD-DVD"
      baseuri: "{{bmc_address}}"
      username: "{{ bmc_user }}"
      password: "{{ bmc_password }}"

- name: Reboot
  redfish_command:
    category: Systems
    command: PowerForceRestart
    baseuri: "{{bmc_address}}"
    username: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
  register: result
  ignore_errors: True
