---
- name: Install needed packages
  yum:
    name:
      - python3-pip
      - openssl-devel
      - make
      - podman
      - skopeo
      - jq
      - git
    state: present

- name: Create temporary directory
  tempfile:
    state: directory
  register: temporary_directory

- name: Install golang
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items:
    - "curl {{ golang_url | default('https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz') }} -o {{ temporary_directory.path }}/go.tar.gz"
    - "tar -zxvf {{ temporary_directory.path }}/go.tar.gz -C /usr/local/"
    - "echo 'export GOROOT=/usr/local/go' | tee -a /etc/profile"
    - "echo 'export PATH=$PATH:/usr/local/go/bin' | tee -a /etc/profile"
