---
- name: Create a temporary file
  tempfile:
    state: file
  register: tempfile_pullsecret

- name: Copy pull secret to file
  copy:
    content: "{{ pull_secret }}"
    dest: "{{ tempfile_pullsecret.path }}"

- name: Create cluster and download ISO
  block:
    - name: Create new AI cluster
      shell: "aicli create cluster -P pull_secret={{ tempfile_pullsecret.path }} -P base_dns_domain={{ cluster_domain }} -P ssh_public_key='{{ ssh_public_key }}' -P high_availability_mode=None -P openshift_version='{{ cluster_version }}' {{ cluster_name }}"

    - name: Retrieve cluster ID from name
      shell: "aicli list cluster | grep {{ cluster_name }} | cut -d '|' -f3 | tr -d ' '"
      register: cluster_id

    - name: Set the right network type
      uri:
        url: "{{ ai_url }}/api/assisted-install/v1/clusters/{{ cluster_id.stdout }}/install-config"
        method: PATCH        
        body: '"{\"networking\": {\"networkType\": \"{{ cluster_sdn | default("OVNKubernetes") }}\"}}"'
        body_format: json
        status_code: 201

    - name: Create a temporary file for the template
      tempfile:
        state: file
      register: template_pullsecret

    - name: Generate blob for small ISO with the specific node config
      ansible.builtin.template:
        src: templates/small_iso_request
        dest: "{{ template_pullsecret.path }}"

    - name: Execute call for generating the ISO
      shell: "curl --header \"Content-Type: application/json\" --request POST --data @{{ template_pullsecret.path }} \"{{ ai_url }}/api/assisted-install/v1/clusters/{{ cluster_id.stdout | trim }}/downloads/image\""

    - name: And download it
      shell: "aicli download iso {{ cluster_name }} -p {{ final_iso_path }}"

  environment:
    AI_URL: "{{ ai_url }}"

