---
- name: Deploy single node using manifests
  hosts: provisioner
  environment:
    PATH: "/usr/bin/:/usr/local/bin/:{{ ansible_env.PATH }}"
  roles:
    - role: install-requirements
      tags: install-requirements
    - role: create-vms
      tags: create-vms
    - role: chrony_day0
      tags: generate-manifests
      when: manifests_path is defined and manifests_path|length>0
    - role: mirror-release-image
      tags: mirror-release-image
    - role: deploy_cluster_with_policy
      tags: deploy-cluster-with-policy
      vars:
        add_extra_workers: false
    - role: add-extra-workers
      tags: add-extra-workers
    - role: deploy_cluster_with_policy
      vars:
        add_extra_workers: true
      tags: add-extra-workers        
