- name: debug
  debug:
    var: redfish_ips

- name: Get IP of the registry vm
  shell: "kcli info vm {{ provisioner_cluster_name }}-installer -f ip -v"
  register: disconnecter_vm

- name: Get IP of master vms
  shell: "kcli info vm {{ provisioner_cluster_name }}-master-0 -f ip -v ;  kcli info vm {{ provisioner_cluster_name }}-master-1 -f ip -v;  kcli info vm {{ provisioner_cluster_name }}-master-2 -f ip -v"
  register: master_vms

- name: Create tmp directory for haproxy
  tempfile:
    state: directory
  register: tempdiroutput

- name: Copy template to temporary directory
  template:
    src: "./templates/create_haproxy.sh.j2"
    dest: "{{ tempdiroutput.path }}/create_haproxy.sh"
    mode: 0755
  vars:
    master_ips: "{{ master_vms.stdout_lines }}"

- name: Install haproxy
  ansible.builtin.shell:
    cmd: "ssh root@{{ disconnecter_vm.stdout }} 'bash -s' < {{ tempdiroutput.path }}/create_haproxy.sh"
