- name: mirror assisted installer images
  include_role:
    name: "{{ playbook_dir }}/../common-roles/mirror-ai-images"

- name: Download image to temporary directory
  uri:
    url: "{{ rhcos_remote_url }}"
    dest: "{{ http_server_path | default('/var/www/html/') }}/{{ rhcos_remote_url | basename }}"
    creates: "{{ http_server_path | default('/var/www/html/') }}/{{ rhcos_remote_url | basename }}"
  delegate_to: "{{ groups['http_mirror'][0] }}"
